In [1]:
import numpy as np 
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
import warnings
warnings.filterwarnings('ignore')
%matplotlib inline

In [2]:
df = pd.read_csv(r'cardekho_imputated.csv',index_col=[0])
df.head()

,car_name,brand,model,vehicle_age,km_driven,seller_type,fuel_type,transmission_type,mileage,engine,max_power,seats,selling_price
0,Maruti Alto,Maruti,Alto,9,120000,Individual,Petrol,Manual,19.70,796,46.30,5,120000
1,Hyundai Grand,Hyundai,Grand,5,20000,Individual,Petrol,Manual,18.90,1197,82.00,5,550000
2,Hyundai i20,Hyundai,i20,11,60000,Individual,Petrol,Manual,17.00,1197,80.00,5,215000
3,Maruti Alto,Maruti,Alto,9,37000,Individual,Petrol,Manual,20.92,998,67.10,5,226000
4,Ford Ecosport,Ford,Ecosport,6,30000,Dealer,Diesel,Manual,22.77,1498,98.59,5,570000

In [3]:
df.isnull().sum()

car_name             0
brand                0
model                0
vehicle_age          0
km_driven            0
seller_type          0
fuel_type            0
transmission_type    0
mileage              0
engine               0
max_power            0
seats                0
selling_price        0
dtype: int64

In [4]:
df.drop('car_name',inplace=True,axis=1)
df.drop('brand',inplace=True,axis=1)

In [5]:
df.head()
df.isnull().sum()

model                0
vehicle_age          0
km_driven            0
seller_type          0
fuel_type            0
transmission_type    0
mileage              0
engine               0
max_power            0
seats                0
selling_price        0
dtype: int64

In [6]:
df['model'].unique()
df['model'].value_counts()

model
i20            906
Swift Dzire    890
Swift          781
Alto           778
City           757
              ...
Ghibli           1
Altroz           1
GTC4Lusso        1
Aura             1
Gurkha           1
Name: count, Length: 120, dtype: int64

In [7]:
#Get All Numerical Features
num_features = [feature for feature in df.columns if df[feature].dtype!='O']
print("No. of Numeric Feature: ",len(num_features))
#Get All Categorical Features
cat_features = [feature for feature in df.columns if df[feature].dtype=='O']
print("No. of Categorical  Feature: ",len(cat_features))
#Discrete Features
descrete_features = [feature for feature in num_features if len(df[feature].unique())<=25]
print("No. of Discrete Feature: ",len(descrete_features))
#Contimuos Features
continous_features = [feature for feature in num_features if feature not in descrete_features]
print("No. of Continoues Feature: ",len(continous_features))

No. of Numeric Feature:  7
No. of Categorical  Feature:  4
No. of Discrete Feature:  2
No. of Continoues Feature:  5

In [8]:
#Splittion data
from sklearn.model_selection import train_test_split
X= df.drop(['selling_price'],axis=1)
y = df['selling_price']

In [9]:
df.head()

,model,vehicle_age,km_driven,seller_type,fuel_type,transmission_type,mileage,engine,max_power,seats,selling_price
0,Alto,9,120000,Individual,Petrol,Manual,19.70,796,46.30,5,120000
1,Grand,5,20000,Individual,Petrol,Manual,18.90,1197,82.00,5,550000
2,i20,11,60000,Individual,Petrol,Manual,17.00,1197,80.00,5,215000
3,Alto,9,37000,Individual,Petrol,Manual,20.92,998,67.10,5,226000
4,Ecosport,6,30000,Dealer,Diesel,Manual,22.77,1498,98.59,5,570000

In [10]:
print(type(X))
print(X.shape)

<class 'pandas.core.frame.DataFrame'>
(15411, 10)

In [11]:
#Feature Encoding and Scaling
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X['model']=le.fit_transform(X['model'])

In [12]:
num_features=X.select_dtypes(exclude='object').columns
onehot_columns = ['seller_type','fuel_type','transmission_type']

from sklearn.preprocessing import OneHotEncoder,StandardScaler
from sklearn.compose import ColumnTransformer

numeric_trasformer = StandardScaler()
oh_transformer =OneHotEncoder(drop='first')

preprocessor =ColumnTransformer(
    [
        ("OneHotEncoder",oh_transformer,onehot_columns),
        ("StandardScaler",numeric_trasformer,num_features)
    ],remainder='passthrough'
)

In [13]:
X= preprocessor.fit_transform(X)

In [14]:
pd.DataFrame(X)

,0,1,2,3,4,5,6,7,8,9,10,11,12,13
0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,-1.519714,0.983562,1.247335,-0.000276,-1.324259,-1.263352,-0.403022
1,1.0,0.0,0.0,0.0,0.0,1.0,1.0,-0.225693,-0.343933,-0.690016,-0.192071,-0.554718,-0.432571,-0.403022
2,1.0,0.0,0.0,0.0,0.0,1.0,1.0,1.536377,1.647309,0.084924,-0.647583,-0.554718,-0.479113,-0.403022
3,1.0,0.0,0.0,0.0,0.0,1.0,1.0,-1.519714,0.983562,-0.360667,0.292211,-0.936610,-0.779312,-0.403022
4,0.0,0.0,1.0,0.0,0.0,0.0,1.0,-0.666211,-0.012060,-0.496281,0.735736,0.022918,-0.046502,-0.403022
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15406,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.508844,0.983562,-0.869744,0.026096,-0.767733,-0.757204,-0.403022
15407,0.0,0.0,0.0,0.0,0.0,1.0,1.0,-0.556082,-1.339555,-0.728763,-0.527711,-0.216964,-0.220803,2.073444
15408,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.407551,-0.012060,0.220539,0.344954,0.022918,0.068225,-0.403022
15409,0.0,0.0,1.0,0.0,0.0,0.0,1.0,1.426247,-0.343933,72.541850,-0.887326,1.329794,0.917158,2.073444
15410,0.0,0.0,0.0,0.0,0.0,1.0,0.0,-1.024131,-1.339555,-0.825631,-0.407839,0.020999,0.395884,-0.403022

In [15]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.25,random_state=42)

Model Training

In [16]:
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import Ridge
from sklearn.linear_model import Lasso
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.neighbors import KNeighborsRegressor
from sklearn.metrics import (
    mean_absolute_error,
    mean_squared_error,
    r2_score
)

In [17]:
#Create a function to Evaluate Model
def evaluate_model(true,predicted):
    mae = mean_absolute_error(true, predicted)
    mse = mean_squared_error(true, predicted)
    rmse = np.sqrt(mean_squared_error(true, predicted))
    r2 = r2_score(true, predicted)
    return mae,rmse,r2

In [18]:
models = {
    "Linear Regression": LinearRegression(),
    "Ridge": Ridge(),
    "Lasso": Lasso(),
    "Decision Tree": DecisionTreeRegressor(),
    "Random Forest": RandomForestRegressor(),
    "KNN": KNeighborsRegressor()
}
for i in range(len(list(models))):
    model = list(models.values())[i]
    model.fit(X_train,y_train)

    
    #Make Predictions
    y_train_pred = model.predict(X_train)
    y_test_pred = model.predict(X_test)

    #Evaluate Train and Test Dataset
    model_train_mae,model_train_rmse,model_train_r2=evaluate_model(y_train,y_train_pred)

    model_test_mae,model_test_rmse,model_test_r2=evaluate_model(y_test,y_test_pred)

    print(list(models.keys())[i])

    print("Model Performance for Training Set")
    print("-Root Mean Squared Error: {:.4f}".format(model_train_rmse))
    print("-Mean Absolute Error: {:.4f}".format(model_train_mae))
    print("-R2_Score: {:.4f}".format(model_train_r2))

    print("--------------------------------------------------")

    print("Model Performance for Testing Set")
    print("-Root Mean Squared Erro: {:.4f}".format(model_test_rmse))
    print("-Mean Absolute Error: {:.4f}".format(model_test_mae))
    print("-R2_Score: {:.4f}".format(model_test_r2))

    print("="*50)

Linear Regression
Model Performance for Training Set
-Root Mean Squared Error: 552154.2495
-Mean Absolute Error: 266675.1076
-R2_Score: 0.6220
--------------------------------------------------
Model Performance for Testing Set
-Root Mean Squared Erro: 519891.2635
-Mean Absolute Error: 284283.4460
-R2_Score: 0.6525
==================================================
Ridge
Model Performance for Training Set
-Root Mean Squared Error: 552154.8775
-Mean Absolute Error: 266635.3662
-R2_Score: 0.6220
--------------------------------------------------
Model Performance for Testing Set
-Root Mean Squared Erro: 519880.3842
-Mean Absolute Error: 284241.1129
-R2_Score: 0.6525
==================================================
Lasso
Model Performance for Training Set
-Root Mean Squared Error: 552154.2607
-Mean Absolute Error: 266674.0472
-R2_Score: 0.6220
--------------------------------------------------
Model Performance for Testing Set
-Root Mean Squared Erro: 519890.5730
-Mean Absolute Error: 284283.7890
-R2_Score: 0.6525
==================================================
Decision Tree
Model Performance for Training Set
-Root Mean Squared Error: 20644.8585
-Mean Absolute Error: 4991.7517
-R2_Score: 0.9995
--------------------------------------------------
Model Performance for Testing Set
-Root Mean Squared Erro: 327613.2847
-Mean Absolute Error: 133071.0464
-R2_Score: 0.8620
==================================================
Random Forest
Model Performance for Training Set
-Root Mean Squared Error: 140547.3885
-Mean Absolute Error: 39657.5187
-R2_Score: 0.9755
--------------------------------------------------
Model Performance for Testing Set
-Root Mean Squared Erro: 242111.8451
-Mean Absolute Error: 105446.9410
-R2_Score: 0.9246
==================================================
KNN
Model Performance for Training Set
-Root Mean Squared Error: 329513.6929
-Mean Absolute Error: 90967.5376
-R2_Score: 0.8654
--------------------------------------------------
Model Performance for Testing Set
-Root Mean Squared Erro: 280676.9784
-Mean Absolute Error: 116579.3732
-R2_Score: 0.8987
==================================================

In [19]:
#Initialize few parameter for HyperParameter tunning 
knn_params= {"n_neighbors":[2,3,10,20,40,50]}
rf_params ={
    "max_depth":[5,8,15,10],#"max_depth":[5,8,15,10,None]
    "n_estimators":[100,200,500],#"n_estimators":[100,200,500,1000]--> It may Make big size Files
    "min_samples_split":[2,8,15,20],
    "max_features":[5,7,'auto',8]
}

In [20]:
randomcvmodels=[
    ("RF",RandomForestRegressor(),rf_params),
    ("KNN",KNeighborsRegressor(),knn_params)
]

In [21]:
from sklearn.model_selection import RandomizedSearchCV
model_param={}
for name,model,params in randomcvmodels:
    random = RandomizedSearchCV(estimator=model,
                                param_distributions=params,
                                n_iter=100,
                                cv=3,
                                verbose=2,
                                n_jobs=-1)
    random.fit(X_train,y_train)
    model_param[name]= random.best_params_

for model_name in model_param:
    print(f"_________________Best Params For {model_name}_________________")
    print(model_param[model_name])

Fitting 3 folds for each of 100 candidates, totalling 300 fits
Fitting 3 folds for each of 6 candidates, totalling 18 fits
_________________Best Params For RF_________________
{'n_estimators': 200, 'min_samples_split': 2, 'max_features': 5, 'max_depth': 15}
_________________Best Params For KNN_________________
{'n_neighbors': 10}

In [32]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.neighbors import KNeighborsRegressor

rf = RandomForestRegressor(
    n_estimators=200,
    min_samples_split=2,
    max_features=5,
    max_depth=15,
    random_state=42
)

knn = KNeighborsRegressor(
    n_neighbors=10
)

rf.fit(X_train, y_train)
knn.fit(X_train, y_train)

KNeighborsRegressor(n_neighbors=10)

In [33]:
rf_pred = rf.predict(X_test)
knn_pred = knn.predict(X_test)

In [34]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import numpy as np

for name, pred in {
    "Random Forest": rf_pred,
    "KNN": knn_pred
}.items():

    mae = mean_absolute_error(y_test, pred)
    mse = mean_squared_error(y_test, pred)
    rmse = np.sqrt(mse)
    r2 = r2_score(y_test, pred)

    print(f"\n{name}")
    print("MAE :", mae)
    print("MSE :", mse)
    print("RMSE:", rmse)
    print("R2  :", r2)

Random Forest
MAE : 100904.23565579561
MSE : 52585495517.85064
RMSE: 229315.27536963305
R2  : 0.932386405085213

KNN
MAE : 121760.29717103556
MSE : 87992360798.24162
RMSE: 296635.06333244155
R2  : 0.8868608200793984

In [35]:
feature_names = preprocessor.get_feature_names_out()

feature_importance = pd.DataFrame({
    "Feature": feature_names,
    "Importance": rf.feature_importances_
})

feature_importance = feature_importance.sort_values(
    by="Importance",
    ascending=False
)

print(feature_importance)

                                        Feature  Importance
12                    StandardScaler__max_power    0.406979
11                       StandardScaler__engine    0.168466
8                   StandardScaler__vehicle_age    0.105935
10                      StandardScaler__mileage    0.103119
9                     StandardScaler__km_driven    0.083929
6       OneHotEncoder__transmission_type_Manual    0.055823
7                         StandardScaler__model    0.038167
13                        StandardScaler__seats    0.020196
2               OneHotEncoder__fuel_type_Diesel    0.009979
5               OneHotEncoder__fuel_type_Petrol    0.004926
0         OneHotEncoder__seller_type_Individual    0.002445
1   OneHotEncoder__seller_type_Trustmark Dealer    0.000025
3             OneHotEncoder__fuel_type_Electric    0.000008
4                  OneHotEncoder__fuel_type_LPG    0.000003

In [36]:
import pickle
pickle.dump(rf, open("car_price_prediction.pkl", "wb"))

In [37]:
pickle.dump(preprocessor, open("preprocessor.pkl", "wb"))

In [38]:
import os

size_mb = os.path.getsize("car_price_prediction.pkl") / (1024 * 1024)
print(f"{size_mb:.2f} MB")

83.85 MB

In [39]:
print(type(rf))

<class 'sklearn.ensemble._forest.RandomForestRegressor'>

In [40]:
import numpy as np

nodes = [tree.tree_.node_count for tree in rf.estimators_]

print("Number of trees:", len(nodes))
print("Average nodes per tree:", np.mean(nodes))
print("Maximum nodes in a tree:", np.max(nodes))

Number of trees: 200
Average nodes per tree: 6102.01
Maximum nodes in a tree: 7729

In [41]:
print(rf.n_estimators)
print(rf.max_depth)

200
15