In [1]:
import numpy as np 
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
import warnings
warnings.filterwarnings('ignore')
%matplotlib inline

In [2]:
df = pd.read_csv('Travel.csv')
df.head()

,CustomerID,ProdTaken,Age,TypeofContact,CityTier,DurationOfPitch,Occupation,Gender,NumberOfPersonVisiting,NumberOfFollowups,ProductPitched,PreferredPropertyStar,MaritalStatus,NumberOfTrips,Passport,PitchSatisfactionScore,OwnCar,NumberOfChildrenVisiting,Designation,MonthlyIncome
0,200000,1,41.0,Self Enquiry,3,6.0,Salaried,Female,3,3.0,Deluxe,3.0,Single,1.0,1,2,1,0.0,Manager,20993.0
1,200001,0,49.0,Company Invited,1,14.0,Salaried,Male,3,4.0,Deluxe,4.0,Divorced,2.0,0,3,1,2.0,Manager,20130.0
2,200002,1,37.0,Self Enquiry,1,8.0,Free Lancer,Male,3,4.0,Basic,3.0,Single,7.0,1,3,0,0.0,Executive,17090.0
3,200003,0,33.0,Company Invited,1,9.0,Salaried,Female,2,3.0,Basic,3.0,Divorced,2.0,1,5,1,1.0,Executive,17909.0
4,200004,0,NaN,Self Enquiry,1,8.0,Small Business,Male,2,3.0,Basic,4.0,Divorced,1.0,0,5,1,0.0,Executive,18468.0

In [3]:
df.isnull().sum()

CustomerID                    0
ProdTaken                     0
Age                         226
TypeofContact                25
CityTier                      0
DurationOfPitch             251
Occupation                    0
Gender                        0
NumberOfPersonVisiting        0
NumberOfFollowups            45
ProductPitched                0
PreferredPropertyStar        26
MaritalStatus                 0
NumberOfTrips               140
Passport                      0
PitchSatisfactionScore        0
OwnCar                        0
NumberOfChildrenVisiting     66
Designation                   0
MonthlyIncome               233
dtype: int64

In [4]:
df['Gender'].value_counts()

Gender
Male       2916
Female     1817
Fe Male     155
Name: count, dtype: int64

In [5]:
df['MaritalStatus'].value_counts()

MaritalStatus
Married      2340
Divorced      950
Single        916
Unmarried     682
Name: count, dtype: int64

In [6]:
df['TypeofContact'].value_counts()

TypeofContact
Self Enquiry       3444
Company Invited    1419
Name: count, dtype: int64

In [7]:
df['Gender'] = df['Gender'].replace('Fe Male','Female')
df['MaritalStatus']= df['MaritalStatus'].replace('Single','Unmarried')

In [8]:
df['MaritalStatus'].value_counts()

MaritalStatus
Married      2340
Unmarried    1598
Divorced      950
Name: count, dtype: int64

In [9]:
df.columns

Index(['CustomerID', 'ProdTaken', 'Age', 'TypeofContact', 'CityTier',
       'DurationOfPitch', 'Occupation', 'Gender', 'NumberOfPersonVisiting',
       'NumberOfFollowups', 'ProductPitched', 'PreferredPropertyStar',
       'MaritalStatus', 'NumberOfTrips', 'Passport', 'PitchSatisfactionScore',
       'OwnCar', 'NumberOfChildrenVisiting', 'Designation', 'MonthlyIncome'],
      dtype='object')

In [10]:
df['Gender'].value_counts()

Gender
Male      2916
Female    1972
Name: count, dtype: int64

In [11]:
#Handling Missing VAlues
features_with_na = [features for features in df.columns if df[features].isnull().sum()>=1]
for feature in features_with_na:
    print(feature,np.round(df[feature].isnull().mean()*100,5), '% missing values')

Age 4.62357 % missing values
TypeofContact 0.51146 % missing values
DurationOfPitch 5.13502 % missing values
NumberOfFollowups 0.92062 % missing values
PreferredPropertyStar 0.53191 % missing values
NumberOfTrips 2.86416 % missing values
NumberOfChildrenVisiting 1.35025 % missing values
MonthlyIncome 4.76678 % missing values

In [12]:
df[features_with_na].select_dtypes(exclude='object').describe()

,Age,DurationOfPitch,NumberOfFollowups,PreferredPropertyStar,NumberOfTrips,NumberOfChildrenVisiting,MonthlyIncome
count,4662.000000,4637.000000,4843.000000,4862.000000,4748.000000,4822.000000,4655.000000
mean,37.622265,15.490835,3.708445,3.581037,3.236521,1.187267,23619.853491
std,9.316387,8.519643,1.002509,0.798009,1.849019,0.857861,5380.698361
min,18.000000,5.000000,1.000000,3.000000,1.000000,0.000000,1000.000000
25%,31.000000,9.000000,3.000000,3.000000,2.000000,1.000000,20346.000000
50%,36.000000,13.000000,4.000000,3.000000,3.000000,1.000000,22347.000000
75%,44.000000,20.000000,4.000000,4.000000,4.000000,2.000000,25571.000000
max,61.000000,127.000000,6.000000,5.000000,22.000000,3.000000,98678.000000

In [13]:
#Inputing Missing Values

In [14]:
#Age 
df.Age.fillna(df.Age.median(),inplace=True)

df.TypeofContact.fillna(df.TypeofContact.mode()[0],inplace=True)

df.DurationOfPitch.fillna(df.DurationOfPitch.median(), inplace= True)

df.NumberOfFollowups.fillna(df.NumberOfFollowups.mode()[0],inplace=True)

df.PreferredPropertyStar.fillna(df.PreferredPropertyStar.mode()[0],inplace=True)

df.NumberOfTrips.fillna(0,inplace=True)

df.NumberOfChildrenVisiting.fillna(df.NumberOfChildrenVisiting.mode()[0],inplace=True)

df.MonthlyIncome.fillna(df.MonthlyIncome.median(),inplace=True)

In [15]:
df.drop('CustomerID', axis=1, inplace=True)

In [16]:
df.head()

,ProdTaken,Age,TypeofContact,CityTier,DurationOfPitch,Occupation,Gender,NumberOfPersonVisiting,NumberOfFollowups,ProductPitched,PreferredPropertyStar,MaritalStatus,NumberOfTrips,Passport,PitchSatisfactionScore,OwnCar,NumberOfChildrenVisiting,Designation,MonthlyIncome
0,1,41.0,Self Enquiry,3,6.0,Salaried,Female,3,3.0,Deluxe,3.0,Unmarried,1.0,1,2,1,0.0,Manager,20993.0
1,0,49.0,Company Invited,1,14.0,Salaried,Male,3,4.0,Deluxe,4.0,Divorced,2.0,0,3,1,2.0,Manager,20130.0
2,1,37.0,Self Enquiry,1,8.0,Free Lancer,Male,3,4.0,Basic,3.0,Unmarried,7.0,1,3,0,0.0,Executive,17090.0
3,0,33.0,Company Invited,1,9.0,Salaried,Female,2,3.0,Basic,3.0,Divorced,2.0,1,5,1,1.0,Executive,17909.0
4,0,36.0,Self Enquiry,1,8.0,Small Business,Male,2,3.0,Basic,4.0,Divorced,1.0,0,5,1,0.0,Executive,18468.0

In [17]:
print(df.columns)
df.isnull().sum()

Index(['ProdTaken', 'Age', 'TypeofContact', 'CityTier', 'DurationOfPitch',
       'Occupation', 'Gender', 'NumberOfPersonVisiting', 'NumberOfFollowups',
       'ProductPitched', 'PreferredPropertyStar', 'MaritalStatus',
       'NumberOfTrips', 'Passport', 'PitchSatisfactionScore', 'OwnCar',
       'NumberOfChildrenVisiting', 'Designation', 'MonthlyIncome'],
      dtype='object')

ProdTaken                   0
Age                         0
TypeofContact               0
CityTier                    0
DurationOfPitch             0
Occupation                  0
Gender                      0
NumberOfPersonVisiting      0
NumberOfFollowups           0
ProductPitched              0
PreferredPropertyStar       0
MaritalStatus               0
NumberOfTrips               0
Passport                    0
PitchSatisfactionScore      0
OwnCar                      0
NumberOfChildrenVisiting    0
Designation                 0
MonthlyIncome               0
dtype: int64

In [18]:
#Feature Engineering

In [19]:
df['TotalVisiting'] = df['NumberOfPersonVisiting']+df['NumberOfChildrenVisiting']
df =df.drop(columns=['NumberOfPersonVisiting','NumberOfChildrenVisiting'])

In [20]:
df.head()

,ProdTaken,Age,TypeofContact,CityTier,DurationOfPitch,Occupation,Gender,NumberOfFollowups,ProductPitched,PreferredPropertyStar,MaritalStatus,NumberOfTrips,Passport,PitchSatisfactionScore,OwnCar,Designation,MonthlyIncome,TotalVisiting
0,1,41.0,Self Enquiry,3,6.0,Salaried,Female,3.0,Deluxe,3.0,Unmarried,1.0,1,2,1,Manager,20993.0,3.0
1,0,49.0,Company Invited,1,14.0,Salaried,Male,4.0,Deluxe,4.0,Divorced,2.0,0,3,1,Manager,20130.0,5.0
2,1,37.0,Self Enquiry,1,8.0,Free Lancer,Male,4.0,Basic,3.0,Unmarried,7.0,1,3,0,Executive,17090.0,3.0
3,0,33.0,Company Invited,1,9.0,Salaried,Female,3.0,Basic,3.0,Divorced,2.0,1,5,1,Executive,17909.0,3.0
4,0,36.0,Self Enquiry,1,8.0,Small Business,Male,3.0,Basic,4.0,Divorced,1.0,0,5,1,Executive,18468.0,2.0

In [21]:
print(df.columns)

Index(['ProdTaken', 'Age', 'TypeofContact', 'CityTier', 'DurationOfPitch',
       'Occupation', 'Gender', 'NumberOfFollowups', 'ProductPitched',
       'PreferredPropertyStar', 'MaritalStatus', 'NumberOfTrips', 'Passport',
       'PitchSatisfactionScore', 'OwnCar', 'Designation', 'MonthlyIncome',
       'TotalVisiting'],
      dtype='object')

In [22]:
#Get All Numerical Features
num_features = [feature for feature in df.columns if df[feature].dtype!='O']
print("No. of Numeric Feature: ",len(num_features))

No. of Numeric Feature:  12

In [23]:
#Get All Categorical Features
cat_features = [feature for feature in df.columns if df[feature].dtype=='O']
print("No. of Numeric Feature: ",len(cat_features))

No. of Numeric Feature:  6

In [24]:
#Discrete Features
descrete_features = [feature for feature in num_features if len(df[feature].unique())<=25]
print("No. of Numeric Feature: ",len(descrete_features))

No. of Numeric Feature:  9

In [25]:
#Contimuos Features
continous_features = [feature for feature in num_features if feature not in descrete_features]
print("No. of Numeric Feature: ",len(continous_features))

No. of Numeric Feature:  3

In [26]:
#Splittion data
from sklearn.model_selection import train_test_split
X= df.drop(['ProdTaken'],axis=1)
y = df['ProdTaken']
X = pd.get_dummies(X, drop_first=True)

In [27]:
y.value_counts()

ProdTaken
0    3968
1     920
Name: count, dtype: int64

In [28]:
X.head()

,Age,CityTier,DurationOfPitch,NumberOfFollowups,PreferredPropertyStar,NumberOfTrips,Passport,PitchSatisfactionScore,OwnCar,MonthlyIncome,...,ProductPitched_Deluxe,ProductPitched_King,ProductPitched_Standard,ProductPitched_Super Deluxe,MaritalStatus_Married,MaritalStatus_Unmarried,Designation_Executive,Designation_Manager,Designation_Senior Manager,Designation_VP
0,41.0,3,6.0,3.0,3.0,1.0,1,2,1,20993.0,...,True,False,False,False,False,True,False,True,False,False
1,49.0,1,14.0,4.0,4.0,2.0,0,3,1,20130.0,...,True,False,False,False,False,False,False,True,False,False
2,37.0,1,8.0,4.0,3.0,7.0,1,3,0,17090.0,...,False,False,False,False,False,True,True,False,False,False
3,33.0,1,9.0,3.0,3.0,2.0,1,5,1,17909.0,...,False,False,False,False,False,False,True,False,False,False
4,36.0,1,8.0,3.0,4.0,1.0,0,5,1,18468.0,...,False,False,False,False,False,False,True,False,False,False

In [29]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.25,random_state=42)

In [30]:
!pip install xgboost

Collecting xgboost
  Downloading xgboost-3.2.0-py3-none-win_amd64.whl.metadata (2.1 kB)
Requirement already satisfied: numpy in c:\users\niraj\anaconda3\lib\site-packages (from xgboost) (2.3.5)
Requirement already satisfied: scipy in c:\users\niraj\anaconda3\lib\site-packages (from xgboost) (1.16.3)
Downloading xgboost-3.2.0-py3-none-win_amd64.whl (101.7 MB)
   ---------------------------------------- 0.0/101.7 MB ? eta -:--:--
   ---------------------------------------- 1.0/101.7 MB 7.4 MB/s eta 0:00:14
    --------------------------------------- 2.4/101.7 MB 5.7 MB/s eta 0:00:18
   - -------------------------------------- 2.9/101.7 MB 4.9 MB/s eta 0:00:21
   - -------------------------------------- 3.7/101.7 MB 4.3 MB/s eta 0:00:23
   - -------------------------------------- 4.2/101.7 MB 4.2 MB/s eta 0:00:24
   - -------------------------------------- 5.0/101.7 MB 3.9 MB/s eta 0:00:25
   -- ------------------------------------- 5.8/101.7 MB 3.9 MB/s eta 0:00:25
   -- ------------------------------------- 6.6/101.7 MB 3.8 MB/s eta 0:00:26
   -- ------------------------------------- 7.3/101.7 MB 3.8 MB/s eta 0:00:25
   --- ------------------------------------ 8.4/101.7 MB 3.9 MB/s eta 0:00:24
   --- ------------------------------------ 9.2/101.7 MB 4.0 MB/s eta 0:00:24
   --- ------------------------------------ 10.0/101.7 MB 3.9 MB/s eta 0:00:24
   ---- ----------------------------------- 10.7/101.7 MB 3.9 MB/s eta 0:00:24
   ---- ----------------------------------- 11.8/101.7 MB 3.9 MB/s eta 0:00:24
   ---- ----------------------------------- 12.3/101.7 MB 3.8 MB/s eta 0:00:24
   ----- ---------------------------------- 12.8/101.7 MB 3.8 MB/s eta 0:00:24
   ----- ---------------------------------- 13.4/101.7 MB 3.7 MB/s eta 0:00:24
   ----- ---------------------------------- 14.2/101.7 MB 3.7 MB/s eta 0:00:24
   ----- ---------------------------------- 14.9/101.7 MB 3.7 MB/s eta 0:00:24
   ------ --------------------------------- 15.7/101.7 MB 3.7 MB/s eta 0:00:24
   ------ --------------------------------- 16.5/101.7 MB 3.7 MB/s eta 0:00:24
   ------ --------------------------------- 17.6/101.7 MB 3.7 MB/s eta 0:00:23
   ------- -------------------------------- 18.4/101.7 MB 3.7 MB/s eta 0:00:23
   ------- -------------------------------- 19.4/101.7 MB 3.8 MB/s eta 0:00:22
   ------- -------------------------------- 19.9/101.7 MB 3.7 MB/s eta 0:00:22
   -------- ------------------------------- 20.7/101.7 MB 3.7 MB/s eta 0:00:22
   -------- ------------------------------- 21.2/101.7 MB 3.7 MB/s eta 0:00:22
   -------- ------------------------------- 22.3/101.7 MB 3.7 MB/s eta 0:00:22
   --------- ------------------------------ 23.3/101.7 MB 3.8 MB/s eta 0:00:21
   --------- ------------------------------ 24.1/101.7 MB 3.8 MB/s eta 0:00:21
   --------- ------------------------------ 24.9/101.7 MB 3.8 MB/s eta 0:00:21
   ---------- ----------------------------- 25.7/101.7 MB 3.7 MB/s eta 0:00:21
   ---------- ----------------------------- 26.5/101.7 MB 3.7 MB/s eta 0:00:21
   ---------- ----------------------------- 27.5/101.7 MB 3.8 MB/s eta 0:00:20
   ----------- ---------------------------- 28.3/101.7 MB 3.7 MB/s eta 0:00:20
   ----------- ---------------------------- 28.8/101.7 MB 3.7 MB/s eta 0:00:20
   ----------- ---------------------------- 29.6/101.7 MB 3.7 MB/s eta 0:00:20
   ------------ --------------------------- 30.7/101.7 MB 3.7 MB/s eta 0:00:19
   ------------ --------------------------- 31.5/101.7 MB 3.8 MB/s eta 0:00:19
   ------------ --------------------------- 32.5/101.7 MB 3.8 MB/s eta 0:00:19
   ------------ --------------------------- 33.0/101.7 MB 3.8 MB/s eta 0:00:19
   ------------- -------------------------- 33.8/101.7 MB 3.7 MB/s eta 0:00:19
   ------------- -------------------------- 34.1/101.7 MB 3.7 MB/s eta 0:00:19
   ------------- -------------------------- 34.6/101.7 MB 3.7 MB/s eta 0:00:19
   ------------- -------------------------- 35.1/101.7 MB 3.6 MB/s eta 0:00:19
   -------------- ------------------------- 35.7/101.7 MB 3.6 MB/s eta 0:00:19
   -------------- ------------------------- 35.9/101.7 MB 3.6 MB/s eta 0:00:19
   -------------- ------------------------- 36.4/101.7 MB 3.5 MB/s eta 0:00:19
   -------------- ------------------------- 37.0/101.7 MB 3.5 MB/s eta 0:00:19
   -------------- ------------------------- 37.5/101.7 MB 3.5 MB/s eta 0:00:19
   --------------- ------------------------ 38.3/101.7 MB 3.5 MB/s eta 0:00:19
   --------------- ------------------------ 38.8/101.7 MB 3.5 MB/s eta 0:00:19
   --------------- ------------------------ 39.3/101.7 MB 3.4 MB/s eta 0:00:19
   --------------- ------------------------ 39.8/101.7 MB 3.4 MB/s eta 0:00:19
   --------------- ------------------------ 40.4/101.7 MB 3.4 MB/s eta 0:00:19
   ---------------- ----------------------- 40.9/101.7 MB 3.4 MB/s eta 0:00:19
   ---------------- ----------------------- 41.4/101.7 MB 3.4 MB/s eta 0:00:18
   ---------------- ----------------------- 41.9/101.7 MB 3.3 MB/s eta 0:00:18
   ---------------- ----------------------- 42.2/101.7 MB 3.3 MB/s eta 0:00:18
   ---------------- ----------------------- 43.0/101.7 MB 3.3 MB/s eta 0:00:18
   ----------------- ---------------------- 43.8/101.7 MB 3.3 MB/s eta 0:00:18
   ----------------- ---------------------- 44.6/101.7 MB 3.3 MB/s eta 0:00:18
   ----------------- ---------------------- 45.1/101.7 MB 3.3 MB/s eta 0:00:18
   ----------------- ---------------------- 45.4/101.7 MB 3.3 MB/s eta 0:00:18
   ------------------ --------------------- 46.1/101.7 MB 3.3 MB/s eta 0:00:17
   ------------------ --------------------- 46.4/101.7 MB 3.3 MB/s eta 0:00:17
   ------------------ --------------------- 46.9/101.7 MB 3.2 MB/s eta 0:00:17
   ------------------ --------------------- 47.4/101.7 MB 3.2 MB/s eta 0:00:17
   ------------------ --------------------- 48.0/101.7 MB 3.2 MB/s eta 0:00:17
   ------------------- -------------------- 48.5/101.7 MB 3.2 MB/s eta 0:00:17
   ------------------- -------------------- 49.0/101.7 MB 3.2 MB/s eta 0:00:17
   ------------------- -------------------- 49.8/101.7 MB 3.2 MB/s eta 0:00:17
   ------------------- -------------------- 50.6/101.7 MB 3.2 MB/s eta 0:00:16
   -------------------- ------------------- 51.4/101.7 MB 3.2 MB/s eta 0:00:16
   -------------------- ------------------- 51.9/101.7 MB 3.2 MB/s eta 0:00:16
   -------------------- ------------------- 52.7/101.7 MB 3.2 MB/s eta 0:00:16
   -------------------- ------------------- 53.2/101.7 MB 3.2 MB/s eta 0:00:16
   --------------------- ------------------ 54.0/101.7 MB 3.2 MB/s eta 0:00:15
   --------------------- ------------------ 54.8/101.7 MB 3.2 MB/s eta 0:00:15
   --------------------- ------------------ 55.3/101.7 MB 3.2 MB/s eta 0:00:15
   ---------------------- ----------------- 56.1/101.7 MB 3.2 MB/s eta 0:00:15
   ---------------------- ----------------- 56.6/101.7 MB 3.2 MB/s eta 0:00:15
   ---------------------- ----------------- 57.4/101.7 MB 3.2 MB/s eta 0:00:14
   ---------------------- ----------------- 57.9/101.7 MB 3.2 MB/s eta 0:00:14
   ----------------------- ---------------- 58.7/101.7 MB 3.2 MB/s eta 0:00:14
   ----------------------- ---------------- 59.5/101.7 MB 3.2 MB/s eta 0:00:14
   ----------------------- ---------------- 60.3/101.7 MB 3.2 MB/s eta 0:00:13
   ------------------------ --------------- 61.1/101.7 MB 3.2 MB/s eta 0:00:13
   ------------------------ --------------- 61.9/101.7 MB 3.2 MB/s eta 0:00:13
   ------------------------ --------------- 62.4/101.7 MB 3.2 MB/s eta 0:00:13
   ------------------------ --------------- 63.2/101.7 MB 3.2 MB/s eta 0:00:12
   ------------------------- -------------- 64.0/101.7 MB 3.2 MB/s eta 0:00:12
   ------------------------- -------------- 64.5/101.7 MB 3.2 MB/s eta 0:00:12
   ------------------------- -------------- 65.3/101.7 MB 3.2 MB/s eta 0:00:12
   ------------------------- -------------- 65.5/101.7 MB 3.2 MB/s eta 0:00:12
   -------------------------- ------------- 66.3/101.7 MB 3.2 MB/s eta 0:00:12
   -------------------------- ------------- 66.6/101.7 MB 3.2 MB/s eta 0:00:11
   -------------------------- ------------- 67.4/101.7 MB 3.2 MB/s eta 0:00:11
   -------------------------- ------------- 67.9/101.7 MB 3.2 MB/s eta 0:00:11
   -------------------------- ------------- 68.4/101.7 MB 3.2 MB/s eta 0:00:11
   --------------------------- ------------ 68.7/101.7 MB 3.2 MB/s eta 0:00:11
   --------------------------- ------------ 68.7/101.7 MB 3.2 MB/s eta 0:00:11
   --------------------------- ------------ 68.9/101.7 MB 3.1 MB/s eta 0:00:11
   --------------------------- ------------ 68.9/101.7 MB 3.1 MB/s eta 0:00:11
   --------------------------- ------------ 68.9/101.7 MB 3.1 MB/s eta 0:00:11
   --------------------------- ------------ 69.2/101.7 MB 3.0 MB/s eta 0:00:11
   --------------------------- ------------ 69.5/101.7 MB 3.0 MB/s eta 0:00:11
   --------------------------- ------------ 70.0/101.7 MB 3.0 MB/s eta 0:00:11
   --------------------------- ------------ 70.5/101.7 MB 3.0 MB/s eta 0:00:11
   --------------------------- ------------ 71.0/101.7 MB 3.0 MB/s eta 0:00:11
   ---------------------------- ----------- 71.8/101.7 MB 3.0 MB/s eta 0:00:10
   ---------------------------- ----------- 72.4/101.7 MB 3.0 MB/s eta 0:00:10
   ---------------------------- ----------- 73.1/101.7 MB 3.0 MB/s eta 0:00:10
   ---------------------------- ----------- 73.7/101.7 MB 3.0 MB/s eta 0:00:10
   ----------------------------- ---------- 74.4/101.7 MB 3.0 MB/s eta 0:00:10
   ----------------------------- ---------- 75.2/101.7 MB 3.0 MB/s eta 0:00:09
   ----------------------------- ---------- 76.0/101.7 MB 3.0 MB/s eta 0:00:09
   ------------------------------ --------- 76.5/101.7 MB 3.0 MB/s eta 0:00:09
   ------------------------------ --------- 77.3/101.7 MB 3.0 MB/s eta 0:00:09
   ------------------------------ --------- 78.1/101.7 MB 3.0 MB/s eta 0:00:08
   ------------------------------ --------- 78.6/101.7 MB 3.0 MB/s eta 0:00:08
   ------------------------------- -------- 79.2/101.7 MB 3.0 MB/s eta 0:00:08
   ------------------------------- -------- 79.7/101.7 MB 3.0 MB/s eta 0:00:08
   ------------------------------- -------- 80.5/101.7 MB 3.0 MB/s eta 0:00:08
   ------------------------------- -------- 81.0/101.7 MB 3.0 MB/s eta 0:00:07
   ------------------------------- -------- 81.3/101.7 MB 3.0 MB/s eta 0:00:07
   -------------------------------- ------- 81.8/101.7 MB 3.0 MB/s eta 0:00:07
   -------------------------------- ------- 82.6/101.7 MB 3.0 MB/s eta 0:00:07
   -------------------------------- ------- 83.4/101.7 MB 3.0 MB/s eta 0:00:07
   -------------------------------- ------- 83.9/101.7 MB 3.0 MB/s eta 0:00:06
   -------------------------------- ------- 83.9/101.7 MB 3.0 MB/s eta 0:00:06
   --------------------------------- ------ 84.1/101.7 MB 3.0 MB/s eta 0:00:06
   --------------------------------- ------ 84.1/101.7 MB 3.0 MB/s eta 0:00:06
   --------------------------------- ------ 84.1/101.7 MB 3.0 MB/s eta 0:00:06
   --------------------------------- ------ 84.4/101.7 MB 2.9 MB/s eta 0:00:06
   --------------------------------- ------ 84.4/101.7 MB 2.9 MB/s eta 0:00:06
   --------------------------------- ------ 84.7/101.7 MB 2.9 MB/s eta 0:00:06
   --------------------------------- ------ 85.2/101.7 MB 2.9 MB/s eta 0:00:06
   --------------------------------- ------ 85.5/101.7 MB 2.9 MB/s eta 0:00:06
   --------------------------------- ------ 86.0/101.7 MB 2.9 MB/s eta 0:00:06
   ---------------------------------- ----- 86.5/101.7 MB 2.8 MB/s eta 0:00:06
   ---------------------------------- ----- 87.0/101.7 MB 2.8 MB/s eta 0:00:06
   ---------------------------------- ----- 87.6/101.7 MB 2.8 MB/s eta 0:00:06
   ---------------------------------- ----- 88.1/101.7 MB 2.8 MB/s eta 0:00:05
   ---------------------------------- ----- 88.6/101.7 MB 2.8 MB/s eta 0:00:05
   ---------------------------------- ----- 88.9/101.7 MB 2.8 MB/s eta 0:00:05
   ----------------------------------- ---- 89.4/101.7 MB 2.8 MB/s eta 0:00:05
   ----------------------------------- ---- 89.7/101.7 MB 2.8 MB/s eta 0:00:05
   ----------------------------------- ---- 90.4/101.7 MB 2.8 MB/s eta 0:00:05
   ----------------------------------- ---- 91.0/101.7 MB 2.7 MB/s eta 0:00:04
   ------------------------------------ --- 91.8/101.7 MB 2.7 MB/s eta 0:00:04
   ------------------------------------ --- 92.3/101.7 MB 2.7 MB/s eta 0:00:04
   ------------------------------------ --- 92.8/101.7 MB 2.7 MB/s eta 0:00:04
   ------------------------------------ --- 93.6/101.7 MB 2.7 MB/s eta 0:00:03
   ------------------------------------ --- 93.8/101.7 MB 2.7 MB/s eta 0:00:03
   ------------------------------------- -- 94.4/101.7 MB 2.7 MB/s eta 0:00:03
   ------------------------------------- -- 95.2/101.7 MB 2.7 MB/s eta 0:00:03
   ------------------------------------- -- 95.2/101.7 MB 2.7 MB/s eta 0:00:03
   ------------------------------------- -- 95.4/101.7 MB 2.7 MB/s eta 0:00:03
   ------------------------------------- -- 95.4/101.7 MB 2.7 MB/s eta 0:00:03
   ------------------------------------- -- 95.4/101.7 MB 2.7 MB/s eta 0:00:03
   ------------------------------------- -- 95.7/101.7 MB 2.6 MB/s eta 0:00:03
   ------------------------------------- -- 95.9/101.7 MB 2.6 MB/s eta 0:00:03
   ------------------------------------- -- 96.2/101.7 MB 2.6 MB/s eta 0:00:03
   -------------------------------------- - 96.7/101.7 MB 2.6 MB/s eta 0:00:02
   -------------------------------------- - 97.5/101.7 MB 2.5 MB/s eta 0:00:02
   -------------------------------------- - 98.0/101.7 MB 2.5 MB/s eta 0:00:02
   -------------------------------------- - 98.6/101.7 MB 2.5 MB/s eta 0:00:02
   ---------------------------------------  99.6/101.7 MB 2.5 MB/s eta 0:00:01
   ---------------------------------------  100.4/101.7 MB 2.5 MB/s eta 0:00:01
   ---------------------------------------  101.2/101.7 MB 2.5 MB/s eta 0:00:01
   ---------------------------------------  101.4/101.7 MB 2.5 MB/s eta 0:00:01
   ---------------------------------------  101.4/101.7 MB 2.5 MB/s eta 0:00:01
   ---------------------------------------- 101.7/101.7 MB 2.5 MB/s  0:00:37
Installing collected packages: xgboost
Successfully installed xgboost-3.2.0

In [31]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
from xgboost import XGBClassifier
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix,precision_score,recall_score,f1_score,roc_auc_score

In [32]:
models={
    "Decision Tree":DecisionTreeClassifier(),
    "Random Forest":RandomForestClassifier(),
    "XGBoostClassifier":XGBClassifier()
}
for i in range(len(list(models))):
    model = list(models.values())[i]
    model.fit(X_train,y_train)

    
    #Make Predictions
    y_train_pred = model.predict(X_train)
    y_test_pred = model.predict(X_test)

    #Training Set Performance
    model_train_accuracy = accuracy_score(y_train,y_train_pred)
    model_train_f1 = f1_score(y_train,y_train_pred,average='weighted')
    model_train_precision = precision_score(y_train,y_train_pred)
    model_train_recall = recall_score(y_train,y_train_pred)
    model_train_rocauc_score = roc_auc_score(y_train,y_train_pred)

    #Testing Set Performance
    model_test_accuracy = accuracy_score(y_test,y_test_pred)
    model_test_f1 = f1_score(y_test,y_test_pred,average='weighted')
    model_test_precision = precision_score(y_test,y_test_pred)
    model_test_recall = recall_score(y_test,y_test_pred)
    model_test_rocauc_score = roc_auc_score(y_test,y_test_pred)

    print(list(models.keys())[i])

    print("Model Performance for Training Set")
    print("-Accuracy: {:.4f}".format(model_train_accuracy))
    print("-F1 Score: {:.4f}".format(model_train_f1))
    print("-Precision: {:.4f}".format(model_train_precision))
    print("-Recall: {:.4f}".format(model_train_recall))
    print("-ROC AUC Score: {:.4f}".format(model_train_rocauc_score))

    print("--------------------------------------------------")

    print("Model Performance for Testing Set")
    print("-Accuracy: {:.4f}".format(model_test_accuracy))
    print("-F1 Score: {:.4f}".format(model_test_f1))
    print("-Precision: {:.4f}".format(model_test_precision))
    print("-Recall: {:.4f}".format(model_test_recall))
    print("-ROC AUC Score: {:.4f}".format(model_test_rocauc_score))

    print("="*50)

Decision Tree
Model Performance for Training Set
-Accuracy: 1.0000
-F1 Score: 1.0000
-Precision: 1.0000
-Recall: 1.0000
-ROC AUC Score: 1.0000
--------------------------------------------------
Model Performance for Testing Set
-Accuracy: 0.9002
-F1 Score: 0.9005
-Precision: 0.7225
-Recall: 0.7354
-ROC AUC Score: 0.8362
==================================================
Random Forest
Model Performance for Training Set
-Accuracy: 1.0000
-F1 Score: 1.0000
-Precision: 1.0000
-Recall: 1.0000
-ROC AUC Score: 1.0000
--------------------------------------------------
Model Performance for Testing Set
-Accuracy: 0.9247
-F1 Score: 0.9179
-Precision: 0.9580
-Recall: 0.6143
-ROC AUC Score: 0.8042
==================================================
XGBoostClassifier
Model Performance for Training Set
-Accuracy: 0.9997
-F1 Score: 0.9997
-Precision: 1.0000
-Recall: 0.9986
-ROC AUC Score: 0.9993
--------------------------------------------------
Model Performance for Testing Set
-Accuracy: 0.9386
-F1 Score: 0.9350
-Precision: 0.9458
-Recall: 0.7040
-ROC AUC Score: 0.8475
==================================================

In [33]:
rf_params ={
    "max_depth":[5,8,15,10],
    "n_estimators":[100,200,300],
    "min_samples_split":[2,8,15,20],
    "max_features":[5,7,'auto',8]
}
xgboost_params={
    "max_depth":[5,8,15,10],
    "n_estimators":[100,200,300],
    "learning_rate":[0.1,0.01],
    "colsample_bytree":[0.3,0.5,0.8,1,0.4]
}

In [36]:
randomcvmodels=[
    ("RF",RandomForestClassifier(),rf_params),
    ("XGB",XGBClassifier(),xgboost_params)
]

In [37]:
from sklearn.model_selection import RandomizedSearchCV
model_param={}
for name,model,params in randomcvmodels:
    random = RandomizedSearchCV(estimator=model,
                                param_distributions=params,
                                n_iter=100,
                                cv=3,
                                verbose=2,
                                n_jobs=-1)
    random.fit(X_train,y_train)
    model_param[name]= random.best_params_

for model_name in model_param:
    print(f"_________________Best Params For {model_name}_________________")
    print(model_param[model_name])

Fitting 3 folds for each of 100 candidates, totalling 300 fits
Fitting 3 folds for each of 100 candidates, totalling 300 fits
_________________Best Params For RF_________________
{'n_estimators': 300, 'min_samples_split': 2, 'max_features': 7, 'max_depth': 15}
_________________Best Params For XGB_________________
{'n_estimators': 200, 'max_depth': 15, 'learning_rate': 0.1, 'colsample_bytree': 0.8}

In [38]:
models={
    "Random Forest":RandomForestClassifier(
    n_estimators=500,
    min_samples_split=2,
    max_features=8,
    max_depth=None
),
    "XGBoostClassifier":XGBClassifier(
    max_depth =15,
    n_estimators =200 ,
    learning_rate =0.1 ,
    colsample_bytree = 0.8
)
}
for i in range(len(list(models))):
    model = list(models.values())[i]
    model.fit(X_train,y_train)

    
    #Make Predictions
    y_train_pred = model.predict(X_train)
    y_test_pred = model.predict(X_test)

    #Training Set Performance
    model_train_accuracy = accuracy_score(y_train,y_train_pred)
    model_train_f1 = f1_score(y_train,y_train_pred,average='weighted')
    model_train_precision = precision_score(y_train,y_train_pred)
    model_train_recall = recall_score(y_train,y_train_pred)
    model_train_rocauc_score = roc_auc_score(y_train,y_train_pred)

    #Testing Set Performance
    model_test_accuracy = accuracy_score(y_test,y_test_pred)
    model_test_f1 = f1_score(y_test,y_test_pred,average='weighted')
    model_test_precision = precision_score(y_test,y_test_pred)
    model_test_recall = recall_score(y_test,y_test_pred)
    model_test_rocauc_score = roc_auc_score(y_test,y_test_pred)

    print(list(models.keys())[i])

    print("Model Performance for Training Set")
    print("-Accuracy: {:.4f}".format(model_train_accuracy))
    print("-F1 Score: {:.4f}".format(model_train_f1))
    print("-Precision: {:.4f}".format(model_train_precision))
    print("-Recall: {:.4f}".format(model_train_recall))
    print("-ROC AUC Score: {:.4f}".format(model_train_rocauc_score))

    print("--------------------------------------------------")

    print("Model Performance for Testing Set")
    print("-Accuracy: {:.4f}".format(model_test_accuracy))
    print("-F1 Score: {:.4f}".format(model_test_f1))
    print("-Precision: {:.4f}".format(model_test_precision))
    print("-Recall: {:.4f}".format(model_test_recall))
    print("-ROC AUC Score: {:.4f}".format(model_test_rocauc_score))

    print("="*50)

Random Forest
Model Performance for Training Set
-Accuracy: 1.0000
-F1 Score: 1.0000
-Precision: 1.0000
-Recall: 1.0000
-ROC AUC Score: 1.0000
--------------------------------------------------
Model Performance for Testing Set
-Accuracy: 0.9354
-F1 Score: 0.9309
-Precision: 0.9557
-Recall: 0.6771
-ROC AUC Score: 0.8351
==================================================
XGBoostClassifier
Model Performance for Training Set
-Accuracy: 1.0000
-F1 Score: 1.0000
-Precision: 1.0000
-Recall: 1.0000
-ROC AUC Score: 1.0000
--------------------------------------------------
Model Performance for Testing Set
-Accuracy: 0.9452
-F1 Score: 0.9426
-Precision: 0.9432
-Recall: 0.7444
-ROC AUC Score: 0.8672
==================================================